config/routes.rb
Todo::Application.routes.draw do
  use_doorkeeper

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1 do
      resources :tasks
      match 'user', to: 'users#show'
    end
  end

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  resources :tasks
  root to: 'tasks#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation
  has_secure_password
  has_many :tasks
end

app/controllers/api/v1/base_controller.rb
module Api
  module V1
    class BaseController < ApplicationController
    private
      def current_user
        if doorkeeper_token
          @current_user ||= User.find(doorkeeper_token.resource_owner_id)
        end
      end
    end
  end
end

app/controllers/api/v1/tasks_controller.rb
module Api
  module V1
    class TasksController < BaseController
      doorkeeper_for :all
      respond_to :json

      def index
        respond_with current_user.tasks
      end

      def create
        respond_with current_user.tasks.create(params[:task])
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < BaseController
      doorkeeper_for :all
      respond_to :json

      def show
        respond_with current_user.as_json(except: :password_digest)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session[:return_to] = params[:return_to] if params[:return_to]
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      if session[:return_to]
        redirect_to session[:return_to]
        session[:return_to] = nil
      else
        redirect_to root_url
      end
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authorize, only: :create

  def index
  end

  def create
    current_user.tasks.create!(params[:task])
    redirect_to tasks_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To Do List</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>To Do List</h1>

<% if current_user %>
  <%= form_for Task.new do |f| %>
    <%= f.text_field :name %>
    <%= f.submit "Add" %>
  <% end %>

  <ul id="tasks">
  <% current_user.tasks.each do |task| %>
    <li><%= task.name %></li>
  <% end %>
  </ul>

  <p id="logged_in">
    Logged in as <strong><%= current_user.name %></strong>.
    <%= link_to "Log Out", logout_path %>
  </p>
<% else %>
  <p><strong>Currently not logged in.</strong></p>
  <p>
    First <%= link_to "Sign Up", signup_path %>
    or <%= link_to "Log In", login_path %>
  </p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>